// This file will be auto-generated by Supabase CLI
// For now, we define the types manually based on our schema

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type UserRole = 'admin' | 'coworking_client' | 'standard_client' | 'visitor';
export type ContentStatus = 'active' | 'draft' | 'archived';
export type PaymentStatus = 'pending' | 'completed' | 'failed' | 'refunded';
export type PaymentMethod = 'stripe' | 'orange_money' | 'mtn_mobile_money';
export type AppointmentStatus = 'pending' | 'confirmed' | 'cancelled' | 'completed' | 'no_show';
export type TimeSlot = 'morning' | 'afternoon' | 'specific';
export type SpaceType = 'individual_office' | 'open_space' | 'meeting_room';
export type SpaceStatus = 'available' | 'occupied' | 'maintenance' | 'reserved';
export type SubscriptionPlan = 'nomade' | 'resident' | 'domiciliation';
export type SubscriptionStatus = 'active' | 'expired' | 'cancelled' | 'pending';
export type BookingStatus = 'pending' | 'confirmed' | 'cancelled' | 'completed';
export type SurveyType = 'creation' | 'service' | 'rh' | 'domiciliation' | 'coworking';
export type SurveyStatus = 'new' | 'in_progress' | 'completed' | 'archived';
export type MessageStatus = 'new' | 'read' | 'replied' | 'archived';
export type BlogCategory = 'fiscalite' | 'rh' | 'strategie' | 'comptabilite' | 'entrepreneuriat' | 'reglementation';
export type DocumentType = 'guides' | 'fiscaux' | 'modeles' | 'notes';

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string;
          first_name: string | null;
          last_name: string | null;
          phone: string | null;
          role: UserRole;
          company_name: string | null;
          avatar_url: string | null;
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          first_name?: string | null;
          last_name?: string | null;
          phone?: string | null;
          role?: UserRole;
          company_name?: string | null;
          avatar_url?: string | null;
          metadata?: Json;
        };
        Update: {
          email?: string;
          first_name?: string | null;
          last_name?: string | null;
          phone?: string | null;
          role?: UserRole;
          company_name?: string | null;
          avatar_url?: string | null;
          metadata?: Json;
        };
      };
      services: {
        Row: {
          id: string;
          slug: string;
          icon_name: string;
          status: ContentStatus;
          order_index: number;
          created_at: string;
          updated_at: string;
          created_by: string | null;
        };
      };
      service_translations: {
        Row: {
          id: string;
          service_id: string;
          language: string;
          title: string;
          short_description: string | null;
          full_description: string | null;
          problematics: string[];
          value_proposition: string | null;
          process_steps: Json;
          features: string[];
        };
      };
      blog_posts: {
        Row: {
          id: string;
          slug: string;
          category: BlogCategory;
          author_id: string | null;
          cover_image_url: string | null;
          published_at: string | null;
          status: ContentStatus;
          views_count: number;
          reading_time: number | null;
          created_at: string;
          updated_at: string;
        };
      };
      blog_post_translations: {
        Row: {
          id: string;
          post_id: string;
          language: string;
          title: string;
          excerpt: string | null;
          content: string | null;
          meta_title: string | null;
          meta_description: string | null;
          tags: string[];
        };
      };
      documentation: {
        Row: {
          id: string;
          type: DocumentType;
          price: number;
          file_url: string;
          file_size: number | null;
          download_count: number;
          status: ContentStatus;
          created_at: string;
          updated_at: string;
        };
      };
      documentation_translations: {
        Row: {
          id: string;
          doc_id: string;
          language: string;
          title: string;
          description: string | null;
        };
      };
      documentation_purchases: {
        Row: {
          id: string;
          doc_id: string;
          user_id: string | null;
          buyer_email: string;
          buyer_name: string;
          buyer_phone: string | null;
          amount_paid: number;
          payment_method: PaymentMethod;
          payment_status: PaymentStatus;
          stripe_payment_id: string | null;
          orange_money_transaction_id: string | null;
          mtn_momo_transaction_id: string | null;
          download_url: string | null;
          downloaded_at: string | null;
          download_count: number;
          expires_at: string | null;
          created_at: string;
          updated_at: string;
        };
      };
      appointments: {
        Row: {
          id: string;
          user_id: string | null;
          first_name: string;
          last_name: string;
          email: string;
          phone: string;
          company_name: string | null;
          service_id: string | null;
          preferred_date: string;
          time_slot: TimeSlot;
          specific_time: string | null;
          message: string | null;
          status: AppointmentStatus;
          confirmed_at: string | null;
          confirmed_by: string | null;
          confirmed_date: string | null;
          confirmed_time: string | null;
          meeting_link: string | null;
          cancellation_reason: string | null;
          admin_notes: string | null;
          created_at: string;
          updated_at: string;
        };
      };
      coworking_spaces: {
        Row: {
          id: string;
          name: string;
          type: SpaceType;
          capacity: number;
          amenities: string[];
          status: SpaceStatus;
          hourly_rate: number | null;
          daily_rate: number | null;
          floor_number: number | null;
          room_number: string | null;
          description: string | null;
          image_url: string | null;
          created_at: string;
          updated_at: string;
        };
      };
      coworking_subscriptions: {
        Row: {
          id: string;
          user_id: string;
          plan_type: SubscriptionPlan;
          space_id: string | null;
          start_date: string;
          end_date: string | null;
          monthly_price: number;
          status: SubscriptionStatus;
          payment_method: PaymentMethod | null;
          stripe_subscription_id: string | null;
          auto_renew: boolean;
          approved_by: string | null;
          approved_at: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
      };
      coworking_bookings: {
        Row: {
          id: string;
          user_id: string;
          space_id: string;
          booking_date: string;
          start_time: string;
          end_time: string;
          purpose: string | null;
          status: BookingStatus;
          participants_count: number;
          equipment_needed: string[];
          approved_by: string | null;
          approved_at: string | null;
          cancellation_reason: string | null;
          created_at: string;
          updated_at: string;
        };
      };
      surveys: {
        Row: {
          id: string;
          survey_type: SurveyType;
          user_id: string | null;
          respondent_name: string;
          respondent_email: string;
          respondent_phone: string;
          responses: Json;
          status: SurveyStatus;
          assigned_to: string | null;
          notes: string | null;
          priority: number;
          follow_up_date: string | null;
          created_at: string;
          updated_at: string;
        };
      };
      contact_messages: {
        Row: {
          id: string;
          user_id: string | null;
          name: string;
          email: string;
          phone: string | null;
          subject: string | null;
          message: string;
          status: MessageStatus;
          replied_at: string | null;
          replied_by: string | null;
          reply_message: string | null;
          priority: number;
          created_at: string;
          updated_at: string;
        };
      };
      solutions: {
        Row: {
          id: string;
          icon_name: string;
          status: ContentStatus;
          demo_url: string | null;
          order_index: number;
          created_at: string;
          updated_at: string;
        };
      };
      solution_translations: {
        Row: {
          id: string;
          solution_id: string;
          language: string;
          title: string;
          description: string | null;
          features: string[];
        };
      };
      audit_logs: {
        Row: {
          id: string;
          user_id: string | null;
          action: string;
          table_name: string | null;
          record_id: string | null;
          old_values: Json | null;
          new_values: Json | null;
          ip_address: string | null;
          user_agent: string | null;
          created_at: string;
        };
      };
    };
    Functions: {
      increment_blog_views: {
        Args: { post_slug: string };
        Returns: void;
      };
      get_available_slots: {
        Args: { check_date: string; service_uuid?: string };
        Returns: { time_slot: string; available: boolean; booked_count: number }[];
      };
      check_space_availability: {
        Args: { space_uuid: string; check_date: string; start_time_param: string; end_time_param: string };
        Returns: boolean;
      };
    };
  };
}
